Name: atcLp

Host: 0.0.0.0
Port: 8000
Mode: debug
MaxBytes: 52428800 # 50MB
Timeout: 100000 # 100000 = 10 seconds
MaxConns: 1000000 # max number of connections
LogsPath: gin.log

chain:
  RPC: ggg
  Contract: 0xdead

mysql:
  DataSource: ***
  MaxIdleCount: 5
  MaxOpenCount: 200
  MaxLifeTime: 3600